#pragma once

#include "test_framework.h"

#define CRYPTOGRAPHY_TEST_NAME crypto

MY_TEST_FUNC(CRYPTOGRAPHY_TEST_NAME, 1);
MY_TEST_FUNC(CRYPTOGRAPHY_TEST_NAME, 2);
MY_TEST_FUNC(CRYPTOGRAPHY_TEST_NAME, 3);
MY_TEST_FUNC(CRYPTOGRAPHY_TEST_NAME, 4);
MY_TEST_FUNC(CRYPTOGRAPHY_TEST_NAME, 5);
MY_TEST_FUNC(CRYPTOGRAPHY_TEST_NAME, 6);
MY_TEST_FUNC(CRYPTOGRAPHY_TEST_NAME, 7);