#pragma once

#include "test_framework.h"

#define PINOUT_UTILS_TEST_NAME pinout_utils

MY_TEST_FUNC(PINOUT_UTILS_TEST_NAME, 1);
MY_TEST_FUNC(PINOUT_UTILS_TEST_NAME, 2);
MY_TEST_FUNC(PINOUT_UTILS_TEST_NAME, 3);
MY_TEST_FUNC(PINOUT_UTILS_TEST_NAME, 4);