FROM ubuntu:latest

RUN sudo apt-get update
RUN sudo apt-get upgrade -y
RUN sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential ninja-build -y