#pragma once

#define OLED_UPDATE_INTERVAL 1000
#define OLED_SDA_PIN 21
#define OLED_SCL_PIN 22

#define GPS_UPDATE_RATE_MS 1000
#define GPS_RX_PIN 16
#define GPS_TX_PIN 17

#define LORA_FREQ 433E6
#define LORA_SCLK_PIN 5
#define LORA_MISO_PIN 19
#define LORA_MOSI_PIN 27
#define LORA_CS_PIN 18
#define LORA_DIO0_PIN 26
#define LORA_RST_PIN 23
#define LORA_DIO1_PIN 33
#define LORA_BUSY_PIN 32