#pragma once

#include "test_framework.h"

#define ACCELEROMETER_TEST_NAME accelerometer

MY_TEST_INIT_FUNC(ACCELEROMETER_TEST_NAME);
MY_TEST_FUNC(ACCELEROMETER_TEST_NAME, 1);
MY_TEST_FUNC_DYNAMIC(ACCELEROMETER_TEST_NAME, 1);