#pragma once

#include "test_framework.h"

#define COMMANDS_TEST_NAME commands

MY_TEST_INIT_FUNC(COMMANDS_TEST_NAME);
MY_TEST_FUNC(COMMANDS_TEST_NAME, 1);
MY_TEST_FUNC(COMMANDS_TEST_NAME, 2);
MY_TEST_FUNC(COMMANDS_TEST_NAME, 3);