#pragma once

#include "test_framework.h"

#define MATHS_TEST_NAME maths

MY_TEST_FUNC(MATHS_TEST_NAME, 1);
MY_TEST_FUNC(MATHS_TEST_NAME, 2);
MY_TEST_FUNC(MATHS_TEST_NAME, 3);
MY_TEST_FUNC(MATHS_TEST_NAME, 4);
MY_TEST_FUNC(MATHS_TEST_NAME, 5);
MY_TEST_FUNC(MATHS_TEST_NAME, 6);
MY_TEST_FUNC(MATHS_TEST_NAME, 7);